# Cross-Camera Re-Identification Configuration
model_path: "data/models/yolov11_players_ball.pt"
model_url: "https://drive.google.com/file/d/1-5fOSHOSB9UXyP_enOoZNAMScrePVcMD/view"
output_dir: "outputs/cross_camera"

detection:
  conf_threshold: 0.5  # Confidence threshold for detections

matching:
  similarity_threshold: 0.7  # Minimum feature similarity for matching
  temporal_window: 5        # Number of frames to consider for temporal consistency
